# A list of Warp Route token configs
# These configs will be merged with the warp routes in the configured registry
# The input here is typically the output of the Hyperlane CLI warp deploy command
---
options: {}
tokens:
  - addressOrDenom: '0x83C7a7d489826F92bDFBcc5DD861Fd0D913f85c6'
    chainName: sepolia
    connections:
      - token: ethereum|starknetsepolia|0x01665b7726bba364f9ef9ba0bee66acfda07a8ad95e2c93d8e88a53d78d7e477
    decimals: 18
    name: Ether
    standard: EvmHypNative
    symbol: ETH
  - addressOrDenom: '0x01665b7726bba364f9ef9ba0bee66acfda07a8ad95e2c93d8e88a53d78d7e477'
    chainName: starknetsepolia
    connections:
      - token: ethereum|sepolia|0x83C7a7d489826F92bDFBcc5DD861Fd0D913f85c6
    decimals: 18
    name: Ether
    standard: StarknetHypSynthetic
    symbol: ETH
