# yaml-language-server: $schema=../schema.json
tokens:
  # Ethereum
  - addressOrDenom: "0xB8fB4E8512c8272e8986058D0318C8cEFcB21aa7"
    chainName: ethereum
    connections:
      - token: cosmosnative|celestia|0x726f757465725f61707000000000000000000000000000010000000000000000
    decimals: 6
    name: TIA
    standard: EvmHypSynthetic
    symbol: TIA
  - addressOrDenom: "0x726f757465725f61707000000000000000000000000000010000000000000000"
    chainName: celestia
    collateralAddressOrDenom: utia
    connections:
      - token: ethereum|ethereum|0xB8fB4E8512c8272e8986058D0318C8cEFcB21aa7
    decimals: 6
    name: TIA
    standard: CosmosNativeHypCollateral
    symbol: TIA
  # Abstract
  - addressOrDenom: "0x638e65eeb89182623E3923A95B1d4b7ED02ADbe0"
    chainName: abstract
    connections:
      - token: cosmosnative|celestia|0x726f757465725f61707000000000000000000000000000010000000000000002
    decimals: 6
    name: TIA
    standard: EvmHypSynthetic
    symbol: TIA
  - addressOrDenom: "0x726f757465725f61707000000000000000000000000000010000000000000002"
    chainName: celestia
    collateralAddressOrDenom: utia
    connections:
      - token: ethereum|abstract|0x638e65eeb89182623E3923A95B1d4b7ED02ADbe0
    decimals: 6
    name: TIA
    standard: CosmosNativeHypCollateral
    symbol: TIA
  # Base
  - addressOrDenom: "0x5d27225a5D8A756e5655617b22cC03616C3B26c3"
    chainName: base
    connections:
      - token: cosmosnative|celestia|0x726f757465725f61707000000000000000000000000000010000000000000001
    decimals: 6
    name: TIA
    standard: EvmHypSynthetic
    symbol: TIA
  - addressOrDenom: "0x726f757465725f61707000000000000000000000000000010000000000000001"
    chainName: celestia
    collateralAddressOrDenom: utia
    connections:
      - token: ethereum|base|0x5d27225a5D8A756e5655617b22cC03616C3B26c3
    decimals: 6
    name: TIA
    standard: CosmosNativeHypCollateral
    symbol: TIA
  # Solana
  - addressOrDenom: "0x726f757465725f61707000000000000000000000000000010000000000000003"
    chainName: celestia
    collateralAddressOrDenom: utia
    connections:
      - token: sealevel|solanamainnet|49UtqAFzuJ8bk2zgYjnGMaU3Z2xVs9n1eFY8Y4dKozyY
    decimals: 6
    name: TIA
    standard: CosmosNativeHypCollateral
    symbol: TIA
  - addressOrDenom: 49UtqAFzuJ8bk2zgYjnGMaU3Z2xVs9n1eFY8Y4dKozyY
    chainName: solanamainnet
    collateralAddressOrDenom: 4PsPuUu4KK8a8kZsbqzTFQiPTriUNbzYyzEyB7bQMNBL
    connections:
      - token: cosmosnative|celestia|0x726f757465725f61707000000000000000000000000000010000000000000003
    decimals: 6
    logoURI: /deployments/warp_routes/TIA/logo.svg
    name: Celestia
    standard: SealevelHypSynthetic
    symbol: TIA
  # Eclipse
  - addressOrDenom: "0x726f757465725f61707000000000000000000000000000010000000000000004"
    chainName: celestia
    collateralAddressOrDenom: utia
    connections:
      - token: sealevel|eclipsemainnet|BpXHAiktwjx7fN6M9ST9wr6qKAsH27wZFhdHEhReJsR6
    decimals: 6
    name: TIA
    standard: CosmosNativeHypCollateral
    symbol: TIA
  - addressOrDenom: 8gkLoHDNA8VygyCD1T7bbDszYboUjALtrxgSLnKZsYBt
    chainName: eclipsemainnet
    collateralAddressOrDenom: CixfcEPw3aAzmXRcgbkaRKCs2wvuWKP2wRB1sBd7ZrPQ
    connections:
      - token: cosmosnative|celestia|0x726f757465725f61707000000000000000000000000000010000000000000004
    decimals: 6
    logoURI: /deployments/warp_routes/TIA/logo.svg
    name: Celestia
    standard: SealevelHypSynthetic
    symbol: TIA
